language: ruby

branches:
  only:
    - rails4
    - master
    - trunk
    - ruby-head-grit

rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  
notifications:
  disabled: true
  
script:
  - bundle exec rspec

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -yqq git-core
 - git init spec/utils/wiki
 
