language: ruby

branches:
  only:
    - master
    - trunk

rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  
matrix:
  allow-failures:
  - rvm: ruby-head

notifications:
  disabled: true
  
script:
  - bundle exec rspec
  - rspec

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -yqq git-core
 - git init spec/utils/wiki
 
