language: ruby

branches:
  only:
    - master
    - trunk
    - ruby-head-grit

rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
env:
  - JRUBY_OPTS="--1.9 -J-XX:+CMSClassUnloadingEnabled -J-XX:+UseConcMarkSweepGC -J-XX:MaxPermSize=256m -J-Xmx1024m -Xcext.enabled=true"
  
matrix:
  exclude:
    - rvm: ruby-head
      jdk: opendjk6
    - rvm: ruby-head
      jdk: oraclejdk7
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: 2.0.0
      jdk: openjdk6

notifications:
  disabled: true
  
script:
  - bundle exec rspec
  - rspec

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -yqq git-core
 - git init spec/utils/wiki
 
