language: ruby

branches:
  only:
    - rails4
    - master
    - trunk

rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  
notifications:
  disabled: true
  
script:
  - bundle exec rspec


before_install:
 - gem install bundler --pre
 - sudo apt-get update -qq
 - git init spec/utils/wiki
 
